### ISSUE TITLE
.find_NA_coercions has problems with dates (?)

### ISSUE THREAD

**Issue by p-mq** [codeblue-team/basecamb#20]
When using .find_NA_coercions on a dataset containing columns with datatype Date, there is an error of class "vctrs_error_incompatible". This happens as part of assembling the "coerced to" column in the return data.frame.

The issue resolves when coercing the data types of "data" to character before.

The error message mentions one column of type factor and one of type Date.

**Comment by Besttd** [comment]
Thanks for your report!

I cannot reproduce this behaviour. The toy example below produces the desired output:

```{r}
data_raw <- data.frame(fct = as.character(c("fact", "fact2")),
                       chr = as.character(c("char", "char2")),
                       num = as.character(c(3, 4)),
                       date = as.character(c("2021-04-22", "2021-04-21")))

data <- data.frame(fct_new = as.factor(c("fact", NA)),
                   chr_new = as.character(c(NA, "char2")),
                   num_new = as.numeric(c(3, NA)),
                   date_new = as.Date(c("2021-04-22", NA)))

data_dictionary <- data.frame(old_column_name = c("fct", "chr", "num", "date"),
                              new_column_name = c("fct_new", "char_new", "num_new", "date_new"),
                              new_data_type = c("factor", "char", "double", "date"))

.find_NA_coercions(data_raw, data, data_dictionary)
#  column  row      value coerced_to
# 1    fct   2      fact2       <NA>
# 2    chr   1       char       <NA>
# 3    num   2          4       <NA>
# 4   date   2 2021-04-21       <NA>
```

**Comment by Besttd** [comment]
Copying from a private conversation with Peter. Peter was able to make some additional observations:

- all columns with `NA`'s  are type `factor`
- the only exception is type `Date`
- if I convert the date column to character, everything is fine
- if I convert the date column to type numeric (becomes double) it still breaks

**Comment by p-mq** [comment]
Update: When removing the Date column, the remaining vector causing the error is of type integer, class factor, with levels (combined levels of the individual factor columns.
If I extract this vector and then append an NA value of type Date, this works fine and creates a vector of type double, class numeric.

My assumption is that somewhere in the internal logic of filtering the data.frame using a matrix the automatic coersion fails - I'm still at a loss to determine when that happens.

**Comment by Besttd** [comment]
Note to self:
- The last column in the returned data frame is actually superfluous because it's obvious that the values were coerced to NA. We suggest to remove the column to circumvent the issue
