### ISSUE TITLE
.find_NA_coersions crahses when not finding coersions

### ISSUE THREAD

**Issue by p-mq** [codeblue-team/basecamb#22]
When building the return data.frame, .find_NA_coersions crashes, because the vectors to assemble it from are some version of empty.

**Comment by p-mq** [comment]
I created a branch fixing this issue. @Besttd Please check if you agree with the proposed solution, and add a test covering this case if you do and create a pull request after. I already checked that apply_data_dictionary does not need to be changed in order to work with the new state.

**Comment by Besttd** [comment]
Added two tests on branch `dev_iss_21`. Both check whether the .find_NA_coercion() functionality works in case no NAs are introduced.

1. testing .find_NA_coercion() alone
2. testing the call to .find_NA_coercion() from apply_data_dictionary()
