### ISSUE TITLE
Check number of factor levels when coercing to factor 

### ISSUE THREAD

**Issue by p-mq** [codeblue-team/basecamb#4]
Affecting functions assign_types_names and apply_data_dictionary:

When not being carful, one can mistakenly assign data type factor to a column that was previously type int or float. In these cases, when a factorial columns with many levels (e.g. >10 & >10% of values in column and no coding specified) are created, issue a warning specifying the column name and number of factor levels. This might prevent absent-mindedness from ruining downstream analysis.

**Comment by Besttd** [comment]
Peter added this feature - Thanks!
